version: "3.9"

services:
  openbravo-pos:
    build: .
    container_name: openbravo-pos
    restart: unless-stopped
    environment:
      - JAVA_HOME=/opt/java/openjdk
    volumes:
      - openbravo-data:/opt/openbravo/data
    network_mode: bridge

volumes:
  openbravo-data:
